name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: echo "Checked out code"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run: echo "Python setup complete"
      
      - name: Install dependencies
        run: echo "Dependencies installed"
      
      - name: Lint code
        run: echo "Linting complete"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: echo "Checked out code"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run: echo "Python setup complete"
      
      - name: Install dependencies
        run: echo "Dependencies installed"
      
      - name: Run tests
        run: echo "Tests complete"
