name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: echo "Checked out code"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run: echo "Python setup complete"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
        run: echo "Dependencies installed"
      
      - name: Lint code
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        run: echo "Linting complete"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: echo "Checked out code"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run: echo "Python setup complete"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        run: echo "Dependencies installed"
      
      - name: Run tests
        run: |
          python -m pytest
        run: echo "Tests complete"
